# Generated by Django 4.0 on 2022-02-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
