# Generated by Django 4.0 on 2022-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_service_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='role',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
