# Generated by Django 4.0 on 2022-02-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_service_role_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='role',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
            preserve_default=False,
        ),
    ]
