# Generated by Django 3.2.8 on 2022-02-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_service_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
