export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_LIST = "GET_PROFILE_LIST";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const PROFILE_FAIL = "PROFILE_FAIL";
